### ISSUE TITLE
clarification on background file

### ISSUE THREAD

**Issue by Mitmischer** [Integrative-Transcriptomics/GO-Compass#47]
I'd like the description and process of obtaining the background file to be clearer.

The website `genome2d.molgenrug.nl` is mentioned as a possible source, but the website has a lot of functionality. Where exactly am I to download the file? Also, note that the website is no longer maintained.

The tool I use for GO analysis provides me with a list of DE genes and total genes per GO term (I'm not sure if the list of total genes is filtered to only contain genes that are in the RNA-Seq data). Is this information valid to create a background file from?

**Comment by ThHarbig** [comment]
Hi!

The background file needs to include the full set of genes and their associated GO terms as it serves as the point of comparison. So if your list is filtered to only contain DE genes it is not valid as a background file.

If your genome reference is deposited at RefSeq or GenBank you can download the GO annotation at Genome2D. http://genome2d.molgenrug.nl/g2d_core_select_RefSeq.php or http://genome2d.molgenrug.nl/g2d_core_select_genbank.php
If it is not deposited in one of these database you can annotate your genome with their service facop: http://facop.molgenrug.nl/.

In any case the identifiers in your list of differentially expressed genes need to match the ones in the background annotation.

Note that Genome2D is not hosted by us, so I can not offer support if anything goes wrong there. In general obtaining GO annotations can be quite hard!

Hope this helps!
